In [1]:
import os
from huggingface_hub import hf_hub_download
from transformers import AutoTokenizer
from src.data_loader.molecule_tokenizer import MoleculeTokenizer

Failed to find the pandas get_adjustment() function to patch
Failed to patch pandas - PandasTools will have limited functionality


In [4]:
# Create tokenizers directory
os.makedirs("./data/tokenizers/", exist_ok=True)

# Method 1: Download tokenizer.json directly
tokenizer_path = hf_hub_download(
    repo_id="bisectgroup/NovoMolGen_32M_SAFE_BPE",
    filename="tokenizer.json",
    local_dir="./data/tokenizers/",
    local_dir_use_symlinks=False
)

print(f"Downloaded tokenizer to: {tokenizer_path}")

Downloaded tokenizer to: data/tokenizers/tokenizer.json


In [6]:
# Method 2: Use AutoTokenizer (alternative)
tokenizer = AutoTokenizer.from_pretrained("bisectgroup/NovoMolGen_32M_SAFE_BPE")
tokenizer.save_pretrained("./data/tokenizers/novomolgen_32M_safe_bpe/")

('./data/tokenizers/novomolgen_32M_safe_bpe/tokenizer_config.json',
 './data/tokenizers/novomolgen_32M_safe_bpe/special_tokens_map.json',
 './data/tokenizers/novomolgen_32M_safe_bpe/tokenizer.json')

In [12]:
# Test the tokenizer
tokenizer_path = "data/tokenizers/novomolgen_32M_safe_bpe/tokenizer.json"
mol_tokenizer = MoleculeTokenizer.load(tokenizer_path)
hf_tokenizer = mol_tokenizer.get_pretrained()

# Test encoding/decoding
test_smiles = "CCOCCNCC=CC=CC=C"
encoded = hf_tokenizer.encode(test_smiles)
decoded = hf_tokenizer.decode(encoded)
print(f"Original: {test_smiles}")
print(f"Encoded: {encoded}")
print(f"Decoded: {decoded}")

Original: CCOCCNCC=CC=CC=C
Encoded: [2, 114, 86, 41, 225, 225, 106, 3]
Decoded: <bos>CCOCCNCC=CC=CC=C<eos>


### write some parser for interview:

In [ ]:
from rdkit import Chem

smi_list = []
with open('test.smi', 'r') as f:
    for line in f:
        smiles = line.strip()
        if smiles:
            smiles = smiles.split()[0]
            smi_list.append(smiles)
            
mol_list = [Chem.MolFromSmiles(smiles) for smiles in smi_list]

In [ ]:
from rdkit import Chem

supplier = Chem.SDMolSupplier('test.sdf')
smi_list = [Chem.MolToSmiles(mol) for mol in supplier if mol is not None]


In [ ]:
import json

with open('test.json', 'r') as f:
    data = json.load(f)

print(data)

In [ ]:
import pandas as pd

df = pd.read_csv('test.csv')
print(df)

In [1]:
import numpy as np

def one_hot(tokens, vocab):
    vocab_index = {v:i for i,v in enumerate(vocab)}
    result = np.zeros((len(tokens), len(vocab)))
    for i, t in enumerate(tokens):
        if t in vocab_index:
            result[i, vocab_index[t]] = 1
    return result

# Test
print(one_hot(['A', 'C', 'G'], ['A','C','G','T']))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [6]:
import numpy as np

def softmax(x):
    x = np.array(x)
    print(x)
    e = np.exp(x)
    print(e)
    return e / e.sum()

print(softmax([1.0, 2.0, 3.0]))


[1. 2. 3.]
[ 2.71828183  7.3890561  20.08553692]
[0.09003057 0.24472847 0.66524096]


In [7]:
def batch_loader(data, batch_size):
    for i in range(0, len(data), batch_size):
        yield data[i:i+batch_size]

# Test
for b in batch_loader([1,2,3,4,5,6], 2):
    print(b)


[1, 2]
[3, 4]
[5, 6]


In [8]:
import numpy as np

def cosine_sim(a, b):
    a = np.array(a)
    b = np.array(b)
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

print(cosine_sim([1,2,3], [2,3,4]))


0.9925833339709303


In [13]:
def rob(nums):
        rob, norob = 0, 0
        for num in nums:
            newRob = norob + num
            newNoRob = max(norob, rob)
            rob, norob = newRob, newNoRob
        return max(rob, norob)

In [17]:
print(rob([5,1,1,9]))

14
